forms:
  sc:
    id: AmgxexBCz7Yh9KbNz2rroy2njsxTNWPbBKF17as89zR6SmqvoJqg
  from:
    encryptionkey: 47DE1RQgpMMc6Ub3L2MeZkHKFTWNotLbnZJP9iL9BJsgqzA1Mg6cQHjXumNDJX64LzdJN8Z42
    password: password

 
#file:
#  path: /Users/owen/toy/board_chain/images/
