forms:
  sc:
    id: Amgrowvv3oLcQBe8ysticYdAJBgQA2P4k8ZmWWv9ruh3BWHFAXwW
  from:
    encryptionkey: 47DE1RQgpMMc6Ub3L2MeZkHKFTWNotLbnZJP9iL9BJsgqzA1Mg6cQHjXumNDJX64LzdJN8Z42
    password: password

 
#file:
#  path: /Users/owen/toy/board_chain/images/
