forms:
  sc:
    id: AmgwHEhtoYjWJVximKzmDBNLT1uw4Am1tzg1EYTK45sfnSabQA6L
  from:
    encryptionkey: 47DE1RQgpMMc6Ub3L2MeZkHKFTWNotLbnZJP9iL9BJsgqzA1Mg6cQHjXumNDJX64LzdJN8Z42
    password: password

 
file:
  path: /home/owen/Desktop/upload/
