forms:
  sc:
    id: Amgodq62AUH3AVrRZWvnzHi9mbHHY3C6mNfEwspzt5w5vV2TDCmG
  from:
    encryptionkey: 47DE1RQgpMMc6Ub3L2MeZkHKFTWNotLbnZJP9iL9BJsgqzA1Mg6cQHjXumNDJX64LzdJN8Z42
    password: password

 
#file:
#  path: /home/owen/Desktop/upload/
