forms:
  sc:
    id: AmfxiJnZT3stDUmvXWGTFBwGjNznx7xnzqmsDGj3GwUYJmMfTcjf
  from:
    encryptionkey: 47DE1RQgpMMc6Ub3L2MeZkHKFTWNotLbnZJP9iL9BJsgqzA1Mg6cQHjXumNDJX64LzdJN8Z42
    password: password

#spring:
#  devtools:
#    livereload:
#      enabled: true
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
#  datasource:
#    username: blocko
#    password: blocko
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL
#    validationQuery: SELECT 1
#    initialization-mode: always
#  h2:
#    console:
#      enabled: true
#    settings:
#      web-allow-others: true
#  jpa:
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      globally_quoted_identifiers: true
#      format_sql: false
#      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
#      show-sql: false
#  session:
#    store-type: jdbc
#    
#file:
#  path: /home/owen/Desktop/upload/
