forms:
  sc:
    id: Amh7gHyi5W7E8wTRYkWgn9RjAvJDiR2aRRc5r79C8jVUUbXwVDTH
  from:
    encryptionkey: 47DE1RQgpMMc6Ub3L2MeZkHKFTWNotLbnZJP9iL9BJsgqzA1Mg6cQHjXumNDJX64LzdJN8Z42
    password: password

 
file:
  path: /home/owen/Desktop/upload/
